//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cephalon.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Cephalon.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I&apos;m sorry Operator, I&apos;m not sure how to help with that.|I&apos;m not sure what you mean, Operator.|I must be malfunctioning - can you repeat that, Operator?.
        /// </summary>
        internal static string ErrorSSML {
            get {
                return ResourceManager.GetString("ErrorSSML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Greetings, Operator! How can I help?|Hello, Operator! How can I help?|Welcome, Operator! How can I help?.
        /// </summary>
        internal static string GreetingSSML {
            get {
                return ResourceManager.GetString("GreetingSSML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It&apos;s {0} on the Plains..
        /// </summary>
        internal static string PlainsTimeCardTitle {
            get {
                return ResourceManager.GetString("PlainsTimeCardTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It is currently {0} on the Plains of Eidolon. The sun will {1} in {2}..
        /// </summary>
        internal static string PlainsTimeSSML {
            get {
                return ResourceManager.GetString("PlainsTimeSSML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} hour{1}.
        /// </summary>
        internal static string TimePartHour {
            get {
                return ResourceManager.GetString("TimePartHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} minute{1}.
        /// </summary>
        internal static string TimePartMinute {
            get {
                return ResourceManager.GetString("TimePartMinute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} second{1}.
        /// </summary>
        internal static string TimePartSecond {
            get {
                return ResourceManager.GetString("TimePartSecond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}.
        /// </summary>
        internal static string TimeReadableOnePart {
            get {
                return ResourceManager.GetString("TimeReadableOnePart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}, {1} and {2}.
        /// </summary>
        internal static string TimeReadableThreeParts {
            get {
                return ResourceManager.GetString("TimeReadableThreeParts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} and {1}.
        /// </summary>
        internal static string TimeReadableTwoParts {
            get {
                return ResourceManager.GetString("TimeReadableTwoParts", resourceCulture);
            }
        }
    }
}
